### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by nicb** [keshavbhatt/Party-Mixer-Qml#1]
Dear Keshav,

thank you for this project! It really looks like what I was looking for... but I can't actually make it run. It seems that it does require ubuntu xenial as a pre-requisite so I will have to run it in a virtual box to try it out. Are there any other strict dependencies that I should know about (I mean besides the Qt/QML framework)? Does the packaging for Android/IOS work? and finally: are you still maintaining this software? :-D

Thank you for a reply...

nicb

**Comment by keshavbhatt** [comment]
No it is abandoned.
This was a two year old project is two years old and i not exactly remember what despendencies i used.
Ty

**Comment by 6guido** [comment]
Perfetto

Inviato da Guido by iPhone
